# Generated by Django 2.2.6 on 2020-03-31 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=50, verbose_name='脚本名称')),
                ('scriptcontent', models.TextField(verbose_name='脚本内容')),
            ],
        ),
        migrations.CreateModel(
            name='Doinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('starttime', models.DateTimeField(verbose_name='开始执行时间')),
                ('endtime', models.DateTimeField(verbose_name='执行结束时间')),
                ('ipcount', models.IntegerField(verbose_name='执行数量')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细')),
                ('jobid', models.IntegerField(verbose_name='jobid')),
                ('status', models.IntegerField(choices=[(1, '未执行'), (2, '正在执行'), (3, '执行成功'), (4, '执行失败')], default=2, verbose_name='执行状态')),
                ('log', models.TextField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblwj.SelectScript', verbose_name='脚本名称')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
