# Generated by Django 2.2.6 on 2020-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=50)),
                ('scriptcontent', models.CharField(max_length=50)),
            ],
        ),
    ]
