# Generated by Django 2.2.6 on 2020-03-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptname', models.CharField(max_length=50)),
                ('scriptcontent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('scriptcontent', models.CharField(max_length=50)),
                ('operatingtime', models.DateTimeField(auto_now_add=True)),
                ('ipcount', models.IntegerField()),
                ('details', models.CharField(max_length=200)),
                ('Celeryid', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('scriptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblwj.SelectScript')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
