# Generated by Django 2.2.6 on 2020-03-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblwj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Do_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('operatingtime', models.DateTimeField(auto_now_add=True)),
                ('ipcount', models.IntegerField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('scriptcontent', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('scriptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joblwj.SelectScript')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
