# Generated by Django 2.2.6 on 2020-04-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblwj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doinfo',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行结束时间'),
        ),
    ]
