# Generated by Django 2.2.6 on 2020-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblwj', '0002_do_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do_info',
            name='ipcount',
            field=models.IntegerField(),
        ),
    ]
