# Generated by Django 2.2.6 on 2020-03-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joblwj', '0003_auto_20200317_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Do_info',
            new_name='Doinfo',
        ),
    ]
