a = [{
        'bk_cpu': 8,
        'bk_isp_name': '1',
        'bk_os_name': 'linux centos',
        'bk_province_name': '110000',
        'bk_host_id': 4,
        'import_from': '3',
        'bk_os_version': '7.6.1810',
        'bk_disk': 49,
        'operator': 'admin',
        'create_time': '2020-03-11T14:17:45.568+08:00',
        'bk_mem': 32011,
        'bk_host_name': 'VM_5_103_centos',
        'last_time': '2020-03-13T16:18:07.646+08:00',
        'bk_host_innerip': '10.0.5.103',
        'bk_comment': '',
        'bk_os_bit': '64-bit',
        'bk_outer_mac': '',
        'bk_asset_id': '',
        'bk_service_term': None,
        'bk_cloud_id': [{
            'bk_obj_name': '',
            'id': '0',
            'bk_obj_id': 'plat',
            'bk_obj_icon': '',
            'bk_inst_id': 0,
            'bk_inst_name': 'default area'
        }],
        'bk_sla': None,
        'bk_cpu_mhz': 1999,
        'bk_host_outerip': '',
        'bk_state_name': 'CN',
        'bk_os_type': '1',
        'bk_mac': '52:54:00:db:06:e3',
        'bk_bak_operator': 'admin',
        'bk_supplier_account': '0',
        'bk_sn': '',
        'bk_cpu_module': 'AMD EPYC Processor'
    }, {
        'bk_cpu': 4,
        'bk_isp_name': '2',
        'bk_os_name': 'linux centos',
        'bk_province_name': '110000',
        'bk_host_id': 5,
        'import_from': '3',
        'bk_os_version': '7.6.1810',
        'bk_disk': 49,
        'operator': 'admin',
        'docker_server_version': '19.03.8',
        'create_time': '2020-03-11T14:17:45.615+08:00',
        'bk_mem': 15885,
        'bk_host_name': 'rbtnode1',
        'last_time': '2020-03-16T09:57:27.79+08:00',
        'bk_host_innerip': '10.0.5.92',
        'bk_comment': '',
        'docker_client_version': '19.03.1',
        'bk_os_bit': '64-bit',
        'bk_outer_mac': '',
        'bk_asset_id': '',
        'bk_service_term': None,
        'bk_cloud_id': [{
            'bk_obj_name': '',
            'id': '0',
            'bk_obj_id': 'plat',
            'bk_obj_icon': '',
            'bk_inst_id': 0,
            'bk_inst_name': 'default area'
        }],
        'bk_sla': None,
        'bk_cpu_mhz': 1999,
        'bk_host_outerip': '',
        'bk_state_name': 'CN',
        'bk_os_type': '1',
        'bk_mac': '52:54:00:03:2e:17',
        'bk_bak_operator': 'admin',
        'bk_supplier_account': '0',
        'bk_sn': '',
        'bk_cpu_module': 'AMD EPYC Processor'
    }, {
        'bk_cpu': 4,
        'bk_isp_name': '3',
        'bk_os_name': 'linux centos',
        'bk_province_name': '110000',
        'bk_host_id': 6,
        'import_from': '3',
        'bk_os_version': '7.6.1810',
        'bk_disk': 49,
        'operator': 'admin',
        'create_time': '2020-03-11T14:17:45.619+08:00',
        'bk_mem': 15885,
        'bk_host_name': 'nginxmongodbpaaszk01zk01zk01-',
        'last_time': '2020-03-13T16:18:32.999+08:00',
        'bk_host_innerip': '10.0.5.118',
        'bk_comment': '',
        'bk_os_bit': '64-bit',
        'bk_outer_mac': '',
        'bk_asset_id': '',
        'bk_service_term': None,
        'bk_cloud_id': [{
            'bk_obj_name': '',
            'id': '0',
            'bk_obj_id': 'plat',
            'bk_obj_icon': '',
            'bk_inst_id': 0,
            'bk_inst_name': 'default area'
        }],
        'bk_sla': None,
        'bk_cpu_mhz': 1999,
        'bk_host_outerip': '',
        'bk_state_name': 'CN',
        'bk_os_type': '1',
        'bk_mac': '52:54:00:9f:90:6b',
        'bk_bak_operator': 'admin',
        'bk_supplier_account': '0',
        'bk_sn': '',
        'bk_cpu_module': 'AMD EPYC Processor'
    }]

for index,b in enumerate(a,1):
    print((index,b['bk_os_name'],b['bk_host_innerip']),end="\n")