a ={
        'message': 'success',
        'code': 0,
        'data': {
            'count': 6,
            'info': [{
                'host': {
                    'bk_cpu': 8,
                    'bk_isp_name': '1',
                    'bk_os_name': 'linux centos',
                    'bk_province_name': '110000',
                    'bk_host_id': 4,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 49,
                    'operator': 'admin',
                    'create_time': '2020-03-11T14:17:45.568+08:00',
                    'bk_mem': 32011,
                    'bk_host_name': 'VM_5_103_centos',
                    'last_time': '2020-03-13T16:18:07.646+08:00',
                    'bk_host_innerip': '10.0.5.103',
                    'bk_comment': '',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': 'CN',
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:db:06:e3',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }, {
                'host': {
                    'bk_cpu': 4,
                    'bk_isp_name': '2',
                    'bk_os_name': 'linux centos',
                    'bk_province_name': '110000',
                    'bk_host_id': 5,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 49,
                    'operator': 'admin',
                    'docker_server_version': '19.03.8',
                    'create_time': '2020-03-11T14:17:45.615+08:00',
                    'bk_mem': 15885,
                    'bk_host_name': 'rbtnode1',
                    'last_time': '2020-03-16T09:57:27.79+08:00',
                    'bk_host_innerip': '10.0.5.92',
                    'bk_comment': '',
                    'docker_client_version': '19.03.1',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': 'CN',
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:03:2e:17',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }, {
                'host': {
                    'bk_cpu': 4,
                    'bk_isp_name': '3',
                    'bk_os_name': 'linux centos',
                    'bk_province_name': '110000',
                    'bk_host_id': 6,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 49,
                    'operator': 'admin',
                    'create_time': '2020-03-11T14:17:45.619+08:00',
                    'bk_mem': 15885,
                    'bk_host_name': 'nginxmongodbpaaszk01zk01zk01-',
                    'last_time': '2020-03-13T16:18:32.999+08:00',
                    'bk_host_innerip': '10.0.5.118',
                    'bk_comment': '',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': 'CN',
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:9f:90:6b',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }, {
                'host': {
                    'bk_cpu': 8,
                    'bk_isp_name': None,
                    'bk_os_name': 'linux centos',
                    'bk_province_name': None,
                    'bk_host_id': 7,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 98,
                    'operator': 'admin',
                    'create_time': '2020-03-11T14:20:19.329+08:00',
                    'bk_mem': 15884,
                    'bk_host_name': 'VM_5_171_centos',
                    'bk_host_innerip': '10.0.5.171',
                    'bk_comment': '',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': None,
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:13:ee:de',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }, {
                'host': {
                    'bk_cpu': 8,
                    'bk_isp_name': None,
                    'bk_os_name': 'linux centos',
                    'bk_province_name': None,
                    'bk_host_id': 8,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 98,
                    'operator': 'admin',
                    'docker_server_version': '19.03.8',
                    'create_time': '2020-03-11T14:20:19.49+08:00',
                    'bk_mem': 15884,
                    'bk_host_name': 'VM_5_25_centos',
                    'bk_host_innerip': '10.0.5.25',
                    'bk_comment': '',
                    'docker_client_version': '19.03.5',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': None,
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:be:e3:d2',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }, {
                'host': {
                    'bk_cpu': 8,
                    'bk_isp_name': None,
                    'bk_os_name': 'linux centos',
                    'bk_province_name': None,
                    'bk_host_id': 9,
                    'import_from': '3',
                    'bk_os_version': '7.6.1810',
                    'bk_disk': 98,
                    'operator': 'admin',
                    'create_time': '2020-03-11T14:21:22.311+08:00',
                    'bk_mem': 15884,
                    'bk_host_name': 'VM_5_51_centos',
                    'bk_host_innerip': '10.0.5.51',
                    'bk_comment': '',
                    'bk_os_bit': '64-bit',
                    'bk_outer_mac': '',
                    'bk_asset_id': '',
                    'bk_service_term': None,
                    'bk_cloud_id': [{
                        'bk_obj_name': '',
                        'id': '0',
                        'bk_obj_id': 'plat',
                        'bk_obj_icon': '',
                        'bk_inst_id': 0,
                        'bk_inst_name': 'default area'
                    }],
                    'bk_sla': None,
                    'bk_cpu_mhz': 1999,
                    'bk_host_outerip': '',
                    'bk_state_name': None,
                    'bk_os_type': '1',
                    'bk_mac': '52:54:00:d5:23:58',
                    'bk_bak_operator': 'admin',
                    'bk_supplier_account': '0',
                    'bk_sn': '',
                    'bk_cpu_module': 'AMD EPYC Processor'
                },
                'set': [],
                'biz': [],
                'module': []
            }]
        },
        'result': True,
        'request_id': '42461311a7ab49df80ae75e24e792f5f'
    }


print(a[0],a[1])
